---
# Install fluentbit

- name: Install | Install packages to allow HTTPS installation
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - ca-certificates
      - curl

- name: Ensure keyrings directory is created
  ansible.builtin.file:
    path: "{{ apt_keyrings_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download Fluentbit GPG key.
  ansible.builtin.get_url:
    url: "{{ fluentbit_gpg_key }}"
    dest: "{{ fluentbit_apt_gpg_key }}"
    mode: '0644'
    force: true

- name: Install | Add fluent-bit repository
  ansible.builtin.apt_repository:
    repo: '{{ fluentbit_apt_repo }}'
    state: present
    update_cache: true

- name: Install | Install fluentbit package
  package:
    name: "{{ fluentbit_pkg }}"
    state: present
    update_cache: true
  notify: Restart Fluentbit service
  tags: ['install']
